config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      patch :complete
    end
  end

  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    # @items = Item.all.order("created_at desc")
    # prevent when others user signed up look at your items
    if user_signed_in?
      @items = Item.where(user_id: current_user.id).order("created_at desc")
    end
  end

  def show
    # same as find_item
    # need before_action
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item) # show page
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def complete
    find_item
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end

  private

    def find_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.haml
= simple_form_for @item do |f|
  = f.input :title, label: "item"
  = f.input :description
  = f.button :submit

app/views/items/edit.haml
.col-md-6.col-md-offset-3
  %h1 Edit Item

  = render 'form'

app/views/items/index.haml
/ Checks to see if a user is signed in, if one is, it will list its checklist.
/ If not, it will render the landing page that asks the user to sign up or login.
- if user_signed_in?
  .col-md-6.col-md-offset-3
    - @items.each do |item|
      .index-wrapper
        - if item.completed?
          .row.item
            .col-md-8
              %h2.item-title{:style => "opacity: 0.5;"}
                %strike= link_to item.title, item
              %p.item-sub-title.item-desc{:style => "opacity: 0.5;"}
                - p= truncate(item.description, length: 200)
              %p.time-created-at.item-sub-title{:style => "opacity: 0.5;"}
                Completed #{time_ago_in_words(item.completed_at)} ago
            .col-md-2
              %p
                = link_to complete_item_path(item), method: :patch do
                  %i.fa.fa-check.fa-lg
            .col-md-2
              %p
                = link_to item, method: :delete, data: { confirm: "Are you sure?" } do
                  %i.fa.fa-trash.fa-lg
        - else
          .row.item
            .col-md-8
              %h2.item-title= link_to item.title, item
              %p.item-sub-title.item-desc
                - p= truncate(item.description, length: 200)
              %p.time-created-at.item-sub-title{:style => "opacity: 0.5;"}
                Created #{time_ago_in_words(item.created_at)} ago
            .col-md-2
              %p
                = link_to complete_item_path(item), method: :patch do
                  %i.fa.fa-check.fa-lg
            .col-md-2
              %p
                = link_to item, method: :delete, data: { confirm: "Are you sure?" } do
                  %i.fa.fa-trash.fa-lg
- else
  = render 'layouts/static_landing_page'

app/views/items/new.haml
.col-md-6.col-md-offset-3
  %h1 new checklist item

  = render 'form'

app/views/items/show.haml
.col-md-6.col-md-offset-3
  %h2= @item.title
  %p= @item.description

  = link_to "Back", root_path
  = link_to 'Edit', edit_item_path(@item)

app/views/layouts/_static_landing_page.haml
.jumbotron
  %h1 Checklist APP
  %p keep track your stuff
  = link_to "Sign Up", new_user_registration_path, class: "btn btn-primary"
  = link_to "Log in", new_user_session_path, class: "btn btn-primary"

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Checklist
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to "Checklist", root_path, class: "navbar-brand"
        %ul.nav.navbar-nav
          %li= link_to "Sign Up", new_user_registration_path
          - if current_user.present?
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Log in", new_user_session_path
        - if user_signed_in?
          = link_to "New Item", new_item_path, class: "navbar-text navbar-link navbar-right"

    %p.notice= notice
    %p.alert= alert
  .container
    = yield